# Use official Java 17 runtime
FROM openjdk:17-jdk-slim

# Set working directory inside the container
WORKDIR /app

# Copy the Spring Boot JAR into the container
COPY target/PasteBin-0.0.1-SNAPSHOT.jar app.jar

# Expose the port your app runs on
EXPOSE 8080

# Run the JAR when container starts
ENTRYPOINT ["java", "-jar", "app.jar"]
